//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientdotNET.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ServiceReference1.BqService")]
    public interface BqService {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BqService/getCompteRequest", ReplyAction="http://ws/BqService/getCompteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientdotNET.ServiceReference1.getCompteResponse getCompte(ClientdotNET.ServiceReference1.getCompteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BqService/getCompteRequest", ReplyAction="http://ws/BqService/getCompteResponse")]
        System.Threading.Tasks.Task<ClientdotNET.ServiceReference1.getCompteResponse> getCompteAsync(ClientdotNET.ServiceReference1.getCompteRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BqService/ConversionEuroToDhRequest", ReplyAction="http://ws/BqService/ConversionEuroToDhResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientdotNET.ServiceReference1.ConversionEuroToDhResponse ConversionEuroToDh(ClientdotNET.ServiceReference1.ConversionEuroToDhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BqService/ConversionEuroToDhRequest", ReplyAction="http://ws/BqService/ConversionEuroToDhResponse")]
        System.Threading.Tasks.Task<ClientdotNET.ServiceReference1.ConversionEuroToDhResponse> ConversionEuroToDhAsync(ClientdotNET.ServiceReference1.ConversionEuroToDhRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BqService/listCompteRequest", ReplyAction="http://ws/BqService/listCompteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientdotNET.ServiceReference1.listCompteResponse listCompte(ClientdotNET.ServiceReference1.listCompteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BqService/listCompteRequest", ReplyAction="http://ws/BqService/listCompteResponse")]
        System.Threading.Tasks.Task<ClientdotNET.ServiceReference1.listCompteResponse> listCompteAsync(ClientdotNET.ServiceReference1.listCompteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class compte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double soldeField;
        
        private int codeField;
        
        private System.DateTime dateCreationField;
        
        private bool dateCreationFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double solde {
            get {
                return this.soldeField;
            }
            set {
                this.soldeField = value;
                this.RaisePropertyChanged("solde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dateCreation {
            get {
                return this.dateCreationField;
            }
            set {
                this.dateCreationField = value;
                this.RaisePropertyChanged("dateCreation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateCreationSpecified {
            get {
                return this.dateCreationFieldSpecified;
            }
            set {
                this.dateCreationFieldSpecified = value;
                this.RaisePropertyChanged("dateCreationSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompte", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getCompteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int code;
        
        public getCompteRequest() {
        }
        
        public getCompteRequest(int code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompteResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getCompteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientdotNET.ServiceReference1.compte @return;
        
        public getCompteResponse() {
        }
        
        public getCompteResponse(ClientdotNET.ServiceReference1.compte @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConversionEuroToDh", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ConversionEuroToDhRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double montant;
        
        public ConversionEuroToDhRequest() {
        }
        
        public ConversionEuroToDhRequest(double montant) {
            this.montant = montant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConversionEuroToDhResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ConversionEuroToDhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public ConversionEuroToDhResponse() {
        }
        
        public ConversionEuroToDhResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listCompte", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listCompteRequest {
        
        public listCompteRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listCompteResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listCompteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientdotNET.ServiceReference1.compte[] @return;
        
        public listCompteResponse() {
        }
        
        public listCompteResponse(ClientdotNET.ServiceReference1.compte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BqServiceChannel : ClientdotNET.ServiceReference1.BqService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BqServiceClient : System.ServiceModel.ClientBase<ClientdotNET.ServiceReference1.BqService>, ClientdotNET.ServiceReference1.BqService {
        
        public BqServiceClient() {
        }
        
        public BqServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BqServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BqServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BqServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientdotNET.ServiceReference1.getCompteResponse ClientdotNET.ServiceReference1.BqService.getCompte(ClientdotNET.ServiceReference1.getCompteRequest request) {
            return base.Channel.getCompte(request);
        }
        
        public ClientdotNET.ServiceReference1.compte getCompte(int code) {
            ClientdotNET.ServiceReference1.getCompteRequest inValue = new ClientdotNET.ServiceReference1.getCompteRequest();
            inValue.code = code;
            ClientdotNET.ServiceReference1.getCompteResponse retVal = ((ClientdotNET.ServiceReference1.BqService)(this)).getCompte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientdotNET.ServiceReference1.getCompteResponse> ClientdotNET.ServiceReference1.BqService.getCompteAsync(ClientdotNET.ServiceReference1.getCompteRequest request) {
            return base.Channel.getCompteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientdotNET.ServiceReference1.getCompteResponse> getCompteAsync(int code) {
            ClientdotNET.ServiceReference1.getCompteRequest inValue = new ClientdotNET.ServiceReference1.getCompteRequest();
            inValue.code = code;
            return ((ClientdotNET.ServiceReference1.BqService)(this)).getCompteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientdotNET.ServiceReference1.ConversionEuroToDhResponse ClientdotNET.ServiceReference1.BqService.ConversionEuroToDh(ClientdotNET.ServiceReference1.ConversionEuroToDhRequest request) {
            return base.Channel.ConversionEuroToDh(request);
        }
        
        public double ConversionEuroToDh(double montant) {
            ClientdotNET.ServiceReference1.ConversionEuroToDhRequest inValue = new ClientdotNET.ServiceReference1.ConversionEuroToDhRequest();
            inValue.montant = montant;
            ClientdotNET.ServiceReference1.ConversionEuroToDhResponse retVal = ((ClientdotNET.ServiceReference1.BqService)(this)).ConversionEuroToDh(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientdotNET.ServiceReference1.ConversionEuroToDhResponse> ClientdotNET.ServiceReference1.BqService.ConversionEuroToDhAsync(ClientdotNET.ServiceReference1.ConversionEuroToDhRequest request) {
            return base.Channel.ConversionEuroToDhAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientdotNET.ServiceReference1.ConversionEuroToDhResponse> ConversionEuroToDhAsync(double montant) {
            ClientdotNET.ServiceReference1.ConversionEuroToDhRequest inValue = new ClientdotNET.ServiceReference1.ConversionEuroToDhRequest();
            inValue.montant = montant;
            return ((ClientdotNET.ServiceReference1.BqService)(this)).ConversionEuroToDhAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientdotNET.ServiceReference1.listCompteResponse ClientdotNET.ServiceReference1.BqService.listCompte(ClientdotNET.ServiceReference1.listCompteRequest request) {
            return base.Channel.listCompte(request);
        }
        
        public ClientdotNET.ServiceReference1.compte[] listCompte() {
            ClientdotNET.ServiceReference1.listCompteRequest inValue = new ClientdotNET.ServiceReference1.listCompteRequest();
            ClientdotNET.ServiceReference1.listCompteResponse retVal = ((ClientdotNET.ServiceReference1.BqService)(this)).listCompte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientdotNET.ServiceReference1.listCompteResponse> ClientdotNET.ServiceReference1.BqService.listCompteAsync(ClientdotNET.ServiceReference1.listCompteRequest request) {
            return base.Channel.listCompteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientdotNET.ServiceReference1.listCompteResponse> listCompteAsync() {
            ClientdotNET.ServiceReference1.listCompteRequest inValue = new ClientdotNET.ServiceReference1.listCompteRequest();
            return ((ClientdotNET.ServiceReference1.BqService)(this)).listCompteAsync(inValue);
        }
    }
}
